# Trigger this workflow when push or pull request to master
# steps:
#   test
#   build docker image
#   test docker image
#   push to dockerhub

# require: github secrets
#    DOCKERHUB_USERNAME
#    DOCKERHUB_PASSWORD
name: test_and_docker_push
on: 
  push: 
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: test 
        run: chmod a+x binary && ./binary
    
      - name: build and push docker with cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image_name: deploy_transparent_singularity_to_cc_template
        #  image_tag: latest
        #  push_image_and_stages: true
        #  pull_image_and_stages: true

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          pkg-config

      - name: Cache Singularity install
        id: cache-singularity
        uses: actions/cache@v2
        with:
          path: /opt/singularity
          key: ${{ runner.os }}-singularity

      - name: Install Singularity
        if: steps.cache-singularity.outputs.cache-hit != 'true'
        env:
          SINGULARITY_VERSION: 3.2.1
        run: |
          export GOPATH=/tmp/go
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p $GOPATH/src/github.com/sylabs && \
          cd $GOPATH/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity && \
          ./mconfig -p /opt/singularity && \
          make -C builddir && \
          sudo make -C builddir install          
 
      - name: Try building container from local docker
        run: |
           singularity build test_container.sif docker-daemon://${GITHUB_REPOSITORY}:latest
         
      - name: Pull Container from docker hub
        run: |
          singularity pull docker://${GITHUB_REPOSITORY}:latest



